task: story_class
description: "Please read the following story and answer if the story is plausible taking into account the order of the events. Please answer with true or false.\n\n\n"
dataset_path: juletxara/GITA4CALAMITA
dataset_name: default
output_type: multiple_choice
test_split: test
fewshot_split: test
doc_to_text: !function utils.doc_to_text
doc_to_target: plausible
doc_to_choice: ["false", "true"]
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0