task: conflict_detec
description: "The following story is implausible. Identify the breakpoint, and then select the sentence responsible for the implausibility. Please identify the breakpoint sentence and the conflicting sentence.\n\n\n"
dataset_path: json
dataset_name: conflict_detec
output_type: multiple_choice
test_split: test
fewshot_split: test
doc_to_text: !function utils.doc_to_text
doc_to_target: !function utils.doc_to_target
doc_to_choice: ['0 and 1', '2 and 4', '1 and 2', '0 and 4', '3 and 4', '0 and 3', '1 and 4', '2 and 3', '0 and 2', '1 and 3']
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
dataset_kwargs:
  data_files:
    test: conflict_detec.jsonl
metadata:
  version: 1.0
